name: changed file by folder
description: return number of changed files
inputs:
  folder:
    description: folder path relative from the root of the folder
    required: true
    default: .
outputs:
  number:
    description: number of files affected
    value: ${{ steps.count-file.outputs.file_count }}
runs:
  using: "composite"
  steps:
    - id: count-file
      run: |
        git remote -v
        git -c protocol.version=2 fetch --no-tags --prune --no-recurse-submodules --depth=1 origin +8d6af6bc7a400bc9acbe36e43d09628af305cc15:refs/remotes/origin/main
        echo "file_count=$(git diff --name-only main ${{ inputs.folder }}|wc -l)" >> $GITHUB_OUTPUT
      shell: bash
