name: changed file by folder
description: return number of changed files
inputs:
  folder:
    description: folder path relative from the root of the folder
    required: true
    default: .
outputs:
  file-count:
    description: number of files affected
    value: ${{ steps.count-file.outputs.file-count }}
runs:
  using: "composite"
  steps:
    - id: count-file
      run: |
        git remote -v
        git -c protocol.version=2 fetch --no-tags --prune --no-recurse-submodules --depth=1 origin +8d6af6bc7a400bc9acbe36e43d09628af305cc15:refs/remotes/origin/main
        git diff --name-only origin/main ${{ inputs.folder }}|wc -l
        echo "file-count=$(git diff --name-only origin/main ${{ inputs.folder }}|wc -l)" >> $GITHUB_OUTPUT
        cat $GITHUB_OUTPUT
      shell: bash
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
